# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'CovidCXR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CovidCXR
  pod 'TensorFlowLiteSwift'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'

end
